version: "3.4"

x-base-php: &base-php
  build:
    context: ./php
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      PHP_VERSION: ${PHP_VERSION:-8.11}
      XDEBUG_VERSION: ${XDEBUG_VERSION:-3.1.4}
  env_file: .env
  working_dir: ${VOLUME_ROOT:-/var/www/html}
  volumes:
    - ../:${VOLUME_ROOT:-/var/www/html}
    - /php/ini/symfony.ini:/usr/local/etc/php/conf.d/999-symfony.ini
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    COMPOSER_HOME: ${VOLUME_ROOT:-/var/www/html}/.composer
    COMPOSER_MEMORY_LIMIT: -1
    HOME: ${VOLUME_ROOT:-/var/www/html}
    XDEBUG_MODE: ${XDEBUG_MODE:-off}
    PHP_IDE_CONFIG: serverName=symfony_6
    XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}

services:
  php:
    <<: *base-php
    ports:
      - '8000:8000'
  
  database:
    image: mysql:8.0
    volumes:
      - database_data:/var/lib/mysql
      - /.docker/database/init.d:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-symfony}
      MYSQL_USER: ${DATABASE_USER:-symfony}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-symfony}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-symfony}
    ports:
      - '3306:3306'

  node:
    image: node
    volumes:
      - ../:${VOLUME_ROOT:-/var/www/html}
    working_dir: ${VOLUME_ROOT:-/var/www/html}

volumes:
  database_data:
    driver: local
